# Available values options are available at https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/values.yaml
global:
  image:
    registry: gsoci.azurecr.io

networkPolicy:
  flavor: cilium
  cilium:
    # Override Cilium Network Policy egress/ingress rules
    egress: []
    ingress: []

psp:
  enabled: true

alloy:
  # You can make the whole chart ineffective by setting enabled to "false"
  enabled: true

  alloy:
    securityContext:
      privileged: true

  image:
    repository: giantswarm/alloy
  configReloader:
    image:
      repository: giantswarm/configmap-reload

  serviceMonitor:
    enabled: true

serviceAccount:
  # -- Whether to create a service account for the Grafana Alloy deployment.
  create: true
