global:
  image:
    registry: gsoci.azurecr.io

networkPolicy:
  flavor: cilium
  cilium:
    # You can override CNP egress/ingress rules
    egress: []
    ingress: []

alloy:
  # You can make the whole chart ineffective by setting enabled to "false"
  enabled: true

  image:
    repository: giantswarm/alloy
  configReloader:
    image:
      repository: giantswarm/configmap-reload

  serviceMonitor:
    enabled: true
