global:
  image:
    registry: gsoci.azurecr.io

alloy:
  # You can make the whole chart ineffective by setting enabled to "false"
  enabled: true

  image:
    repository: giantswarm/alloy
  configReloader:
    image:
      repository: giantswarm/configmap-reload

  serviceMonitor:
    enabled: true
