{{- if eq .Values.networkPolicy.flavor "kubernetes" -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "alloy.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: 12345
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{- end }}
